name: Build, Patch and Push to GitHub Container Registry

on:
  push:
    branches: [ main ]

jobs:
  build-patch-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/myapp:latest

    - name: Patch Container Image with Falcon Sensor
      uses: crowdstrike/falconutil-action@v1
      with:
        falcon_client_id: ${{ vars.FALCON_CLIENT_ID }}
        falcon_region: 'us-1'
        source_image_uri: 'ghcr.io/${{ github.repository_owner }}/myapp:latest'
        target_image_uri: 'ghcr.io/${{ github.repository_owner }}/myapp:patched'
        cid: ${{ secrets.FALCON_CID }}
        image_pull_policy: IfNotPresent
      env:
        FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}

    - name: Push patched image
      run: docker push ghcr.io/${{ github.repository_owner }}/myapp:patched
